# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Keyboard Toturial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Keyboard Toturial


  target 'Keyboard ToturialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Keyboard ToturialUITests' do
    # Pods for testing
  end

end
